# Generated by Django 4.2 on 2024-08-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pamong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nik', models.CharField(max_length=16, unique=True)),
                ('nip', models.CharField(blank=True, max_length=18, null=True, unique=True)),
                ('tempat_lahir', models.CharField(blank=True, max_length=50, null=True)),
                ('tanggal_lahir', models.DateField(blank=True, null=True)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('status_kawin', models.CharField(blank=True, choices=[('Belum Kawin', 'Belum Kawin'), ('Kawin', 'Kawin'), ('Cerai Hidup', 'Cerai Hidup'), ('Cerai Mati', 'Cerai Mati')], max_length=20, null=True)),
                ('pekerjaan', models.CharField(blank=True, max_length=50, null=True)),
                ('jabatan', models.CharField(blank=True, max_length=50, null=True)),
                ('gol_darah', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=2, null=True)),
                ('agama', models.CharField(blank=True, max_length=20, null=True)),
                ('jenis_kelamin', models.CharField(blank=True, choices=[('L', 'L'), ('P', 'P')], max_length=1, null=True)),
                ('masa_jabatan_mulai', models.IntegerField(blank=True, null=True)),
                ('masa_jabatan_selesai', models.IntegerField(blank=True, null=True)),
                ('pendidikan_terakhir', models.CharField(blank=True, max_length=50, null=True)),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
