# Generated by Django 4.2 on 2024-08-05 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pamong',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='base.pamong'),
        ),
    ]
