# Generated by Django 4.2 on 2024-08-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_user_pamong'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password_encrypted',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
