# Generated by Django 4.2 on 2024-08-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_user_password_encrypted_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_encrypted',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
