# Generated by Django 4.2 on 2024-08-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_user_password_encrypted_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password_encrypted',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password_text',
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
