# Generated by Django 4.2 on 2024-08-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_user_password_encrypted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_text',
            field=models.CharField(default=12345678, max_length=128),
            preserve_default=False,
        ),
    ]
