# Generated by Django 4.2 on 2024-08-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password_text',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
